# gdterm - build-time version generation (injected into AssemblyInfo)
#
# Version source chain (highest priority first):
#   1. -CiVersion param  = CI APPVEYOR_BUILD_VERSION (e.g. 0.1.114)
#   2. git describe --long --tags --always --dirty (e.g. 0.1.114-3-g76faca2 / bare sha)
#   3. fallback '0.1.0-dev'
#
# Writes obj\<Configuration>\VersionInfo.g.cs, consumed by the GenerateVersionInfo
# target in Gdterm.UI.csproj before CoreCompile.
# AssemblyVersion/FileVersion use the numeric prefix (padded to 4 segments);
# InformationalVersion keeps the full raw string (incl. git hash) for About box.
# NOTE: keep this file pure ASCII - Windows PowerShell 5.1 misparses UTF-8 w/o BOM as ANSI.
param(
    [Parameter(Mandatory = $true)][string]$OutFile,
    [string]$CiVersion
)
$ErrorActionPreference = 'Stop'

$raw = $null
if ($CiVersion) { $raw = $CiVersion.Trim() }
if (-not $raw) {
    $d = & git describe --long --tags --always --dirty 2>$null
    if ($LASTEXITCODE -eq 0 -and $d) { $raw = (@($d)[0]).ToString().Trim() }
}
if (-not $raw) { $raw = '0.1.0-dev' }

# Numeric prefix for assembly version. Require >=2 dotted segments so a bare git
# sha like '76faca2' is NOT parsed as version 76.0.0.0; fallback is 0.1.0.
$num = '0.1.0'
if ($raw -match '^v?(\d+\.\d+(?:\.\d+){0,2})') { $num = $Matches[1] }
while (($num.Split('.')).Count -lt 4) { $num = "$num.0" }

$dir = Split-Path -Parent $OutFile
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
$lines = @(
    '// <auto-generated>tools/gen-version.ps1 at build time - do not edit</auto-generated>',
    "[assembly: System.Reflection.AssemblyVersion(`"$num`")]",
    "[assembly: System.Reflection.AssemblyFileVersion(`"$num`")]",
    "[assembly: System.Reflection.AssemblyInformationalVersion(`"$raw`")]"
)
Set-Content -Path $OutFile -Value $lines -Encoding Ascii
Write-Host "gen-version: assembly=$num informational=$raw"
exit 0
