# gdterm — 构建时版本号生成（AssemblyInfo 注入）
#
# 版本号唯一权威来源链（优先级从高到低）：
#   1. -CiVersion 参数：CI 传入的 APPVEYOR_BUILD_VERSION（如 0.1.114）
#   2. git describe --long --tags --always --dirty（如 0.1.114-3-g76faca2 / 纯 sha）
#   3. 兜底 0.1.0-dev
#
# 输出 obj\<Configuration>\VersionInfo.g.cs，由 Gdterm.UI.csproj 的
# GenerateVersionInfo Target 在 CoreCompile 前生成并编入程序集。
# AssemblyVersion/FileVersion 取数字部分（如 0.1.114.0）；
# InformationalVersion 保留完整原始描述（含 git hash），关于框直接展示。
param(
    [Parameter(Mandatory = $true)][string]$OutFile,
    [string]$CiVersion
)
$ErrorActionPreference = 'Stop'

$raw = $null
if ($CiVersion) { $raw = $CiVersion.Trim() }
if (-not $raw) {
    $d = & git describe --long --tags --always --dirty 2>$null
    if ($LASTEXITCODE -eq 0 -and $d) { $raw = (@($d)[0]).ToString().Trim() }
}
if (-not $raw) { $raw = '0.1.0-dev' }

# 提取前导数字段作为四段式程序集版本。要求至少两段数字（如 0.1、0.1.114），
# 避免把纯 git sha（如 76faca2）误判为版本 76.0.0.0
$num = '0.1.0'
if ($raw -match '^v?(\d+\.\d+(?:\.\d+){0,2})') { $num = $Matches[1] }
while (($num.Split('.')).Count -lt 4) { $num = "$num.0" }

$dir = Split-Path -Parent $OutFile
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
$lines = @(
    '// <auto-generated>tools/gen-version.ps1 构建时生成 —— 不要手工编辑</auto-generated>',
    "[assembly: System.Reflection.AssemblyVersion(`"$num`")]",
    "[assembly: System.Reflection.AssemblyFileVersion(`"$num`")]",
    "[assembly: System.Reflection.AssemblyInformationalVersion(`"$raw`")]"
)
Set-Content -Path $OutFile -Value $lines -Encoding Ascii
Write-Host "gen-version: assembly=$num informational='$raw'"
exit 0
